;
; language pack "DE" for one file APP: note
;
; @homepage https://ocno.de/
; @copyright 2026 Naki Dal Gelo
; @Licensed under MIT
;
Add note = 'Notiz hinzufügen'
Export = 'Export'
Import = 'Import'
Create new note = 'Neue Notiz erstellen'
Creates a new note that includes a note name and note color = 'Erstellt eine neue Notiz, die einen Notiztitel und eine Notizfarbe enthält.'
Cancel = 'Abbrechen'
Create = 'Erstellen'
Title = 'Titel'
Title of note = 'Titel der Notiz'
Delete = 'Löschen'
Delete a note = 'Eine Notiz löschen'
By clicking on Delete, you delete only the shortcut. If you want to delete a note from the server, first clear the note and the note will be deleted from the server = 'Durch Klicken auf „Löschen“ wird nur die Verknüpfung gelöscht. Wenn Sie eine Notiz vom Server löschen möchten, leeren Sie diese zuerst, somit wird sie vom Server entfernt.'
Edit = 'Bearbeiten'
Edit a note = 'Notiz bearbeiten'
Change the name of the note or the color of the note = 'Ändern Sie den Titel oder die Farbe der Notiz.'
Theme = 'Thema'
There was a problem communicating with the server = 'Es gab ein Problem bei der Kommunikation mit dem Server!'
Password = 'Passwort'
Password protection = 'Passwortschutz'
Set password = 'Passwort festlegen'
Remove password = 'Passwort entfernen'
Print = 'Drucken'
Share = 'Teilen'
File cannot be read = 'Datei kann nicht gelesen werden!'
Setting = 'Einstellungen'
Font = 'Schriftart'
Sans serif = 'Serifenlose'
Serif = 'Serifen'
Monospace = 'Monospace'
Background = 'Hintergrund'
Simple = 'Einfach'
Lined = 'Liniert'
Checkered = 'Kariert'
Dotted = 'Gepunktet'
Fontsize = 'Schriftgröße'
Extra small = 'Sehr klein'
Small = 'Klein'
Medium = 'Mittel'
Large = 'Groß'
Extra large = 'Sehr groß'
Spellcheck = 'Rechtschreibprüfung'
_Yes = 'Ja'
_No = 'Nein'
An error occurred on content paste clipboard data = 'Beim Einfügen von Inhalten aus der Zwischenablage ist ein Fehler aufgetreten!'
An error occurred while trying to share content = 'Beim Versuch, Inhalte zu teilen, ist ein Fehler aufgetreten!'
It is not possible to save, a false password has been entered = 'Kann nicht gespeichert werden, es wurde ein falsches Passwort eingegeben!'
Give the password = 'Geben Sie das Passwort ein'
Unlock = 'Entsperren'
Remove = 'Entfernen'
Do you want to delete the password = 'Möchten Sie das Passwort löschen?'
Enter password to unlock note = 'Geben Sie das Passwort ein, um die Notiz zu entsperren.'
Repeat the password = 'Wiederholen Sie das Passwort'
Password-protected notes are encrypted directly in your browser and sent to the server = 'Passwortgeschützte Nachrichten werden direkt in Ihrem Browser verschlüsselt und an den Server gesendet.'
Remember your password, otherwise you wont be able to decode the note = 'Merken Sie sich Ihr Passwort, sonst können Sie die Nachricht nicht entschlüsseln!'
Do you want to set a password for the note = 'Möchten Sie ein Passwort für die Notiz festlegen?'
Password was not specified = 'Passwort wurde nicht angegeben!'
The passwords do not match = 'Passwörter stimmen nicht überein!'
The given password seems to be incorrect = 'Das eingegebene Passwort scheint falsch zu sein!'
Version = 'Version'
Empty notes list = 'Noch keine Notizen'
No note selected = 'Keine Notiz ausgewählt'
