;
; language pack "RU" for one file APP: note
;
; @homepage https://ocno.de/
; @copyright 2026 Naki Dal Gelo
; @Licensed under MIT
;
Add note = 'Добавить заметку'
Export = 'Экспорт'
Import = 'Импорт'
Create new note = 'Создайте новую заметку'
Creates a new note that includes a note name and note color = 'Создает новую заметку, содержащую название заметки и цвет заметки.'
Cancel = 'Отменить'
Create = 'Создать'
Title = 'Название'
Title of note = 'Название заметки'
Delete = 'Удалить'
Delete a note = 'Удалить заметку'
By clicking on Delete, you delete only the shortcut. If you want to delete a note from the server, first clear the note and the note will be deleted from the server = 'Нажав на Удалить, вы удаляете только ярлык. Если вы хотите удалить заметку с сервера, сначала очистите заметку, и заметка будет удалена с сервера.'
Edit = 'Изменить'
Edit a note = 'Редактировать заметку'
Change the name of the note or the color of the note = 'Изменить  название заметки или цвет оформления заметки.'
Theme = 'Тема'
There was a problem communicating with the server = 'Возникла проблема со связью с сервером!'
Password = 'Пароль'
Password protection = 'Защита паролем'
Set password = 'Установить пароль'
Remove password = 'Удалить пароль'
Print = 'Печатать'
Share = 'Поделиться'
File cannot be read = 'Файл не может быть прочитан!'
Setting = 'Настройки'
Font = 'Шрифт'
Sans serif = 'Без засечек'
Serif = 'С засечками'
Monospace = 'Моноширинный'
Background = 'Фон'
Simple = 'Простой'
Lined = 'Линованный'
Checkered = 'Клетчатый'
Dotted = 'Пунктирный'
Fontsize = 'Размер шрифта'
Extra small = 'Очень мелкий'
Small = 'Мелкий'
Medium = 'Средний'
Large = 'Большой'
Extra large = 'Очень большой'
Spellcheck = 'Проверка орфографии'
_Yes = 'Да'
_No = 'Нет'
An error occurred on content paste clipboard data = 'Произошла ошибка при вставке содержимого из буфер обмена!'
An error occurred while trying to share content = 'Произошла ошибка при попытке поделиться контентом!'
It is not possible to save, a false password has been entered = 'Сохранить невозможно, был указан неверный пароль!'
Give the password = 'Введите пароль'
Unlock = 'Разблокировать'
Remove = 'Удалить'
Do you want to delete the password = 'Вы хотите удалить пароль?'
Enter password to unlock note = 'Введите пароль для разблокировки заметки.'
Repeat the password = 'Повторите пароль'
Password-protected notes are encrypted directly in your browser and sent to the server = 'Защищенные паролем заметки шифруются непосредственно в вашем браузере и отправляются на сервер.'
Remember your password, otherwise you wont be able to decode the note = 'Запомните свой пароль, иначе вы не сможете расшифровать сообщение!'
Do you want to set a password for the note = 'Вы хотите установить пароль для заметки?'
Password was not specified = 'Пароль не был указан!'
The passwords do not match = 'Пароли не совпадают!'
The given password seems to be incorrect = 'Введенный пароль кажется неправильным!'
Version = 'Версия'
Empty notes list = 'Заметок пока нет'
No note selected = 'Заметка не выбрана'
